## **Pre-Work Checklist: Ejecutar antes de comenzar**

Esta etapa inicial prepara el entorno de trabajo para la ejecución del sistema. Aquí se cargan las librerías necesarias, se configuran las rutas a las bases de datos y archivos requeridos, y se establecen las sesiones de Spark. Este paso es fundamental para garantizar que todos los procesos posteriores se ejecuten de manera fluida y sin errores relacionados con la configuración o dependencias del entorno.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install semanticscholar
!pip install pymupdf
!pip install requests
!pip install pdfplumber

Collecting semanticscholar
  Downloading semanticscholar-0.10.0-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: tenacity in /usr/local/lib/python3.11/dist-packages (from semanticscholar) (9.1.2)
Requirement already satisfied: httpx in /usr/local/lib/python3.11/dist-packages (from semanticscholar) (0.28.1)
Requirement already satisfied: nest_asyncio in /usr/local/lib/python3.11/dist-packages (from semanticscholar) (1.6.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx->semanticscholar) (4.9.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx->semanticscholar) (2025.4.26)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx->semanticscholar) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx->semanticscholar) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx->semanticscholar) (0.16.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx->semanticscholar) (1.3.1)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx->semanticscholar) (4.13.2)
Downloading semanticscholar-0.10.0-py3-none-any.whl (22 kB)
Installing collected packages: semanticscholar
Successfully installed semanticscholar-0.10.0
Collecting pymupdf
  Downloading pymupdf-1.26.0-cp39-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.4 kB)
Downloading pymupdf-1.26.0-cp39-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (24.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 79.6 MB/s eta 0:00:00
Installing collected packages: pymupdf
Successfully installed pymupdf-1.26.0
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests) (2025.4.26)
Collecting pdfplumber
  Downloading pdfplumber-0.11.6-py3-none-any.whl.metadata (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 kB 1.5 MB/s eta 0:00:00
Collecting pdfminer.six==20250327 (from pdfplumber)
  Downloading pdfminer_six-20250327-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.11/dist-packages (from pdfplumber) (11.2.1)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-4.30.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.2/48.2 kB 3.5 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20250327->pdfplumber) (3.4.2)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20250327->pdfplumber) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=36.0.0->pdfminer.six==20250327->pdfplumber) (1.17.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20250327->pdfplumber) (2.22)
Downloading pdfplumber-0.11.6-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.2/60.2 kB 4.4 MB/s eta 0:00:00
Downloading pdfminer_six-20250327-py3-none-any.whl (5.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 59.1 MB/s eta 0:00:00
Downloading pypdfium2-4.30.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 79.9 MB/s eta 0:00:00
Installing collected packages: pypdfium2, pdfminer.six, pdfplumber
Successfully installed pdfminer.six-20250327 pdfplumber-0.11.6 pypdfium2-4.30.1

In [ ]:
from configparser import ConfigParser
from pathlib import Path
import requests
import urllib
import json
import pandas as pd
from semanticscholar import SemanticScholar
import os
import pdfplumber
import fitz
from datetime import datetime
import re
from collections import Counter

In [ ]:
!pip install --upgrade openai

import sys
import pyspark.sql.types as T
import pyspark.sql.functions as F
from pyspark.sql.functions import col, explode, from_json, substring, split, udf,lower, expr, regexp_replace, monotonically_increasing_id, trim
from pyspark.sql.types import StringType, StructType, StructField, IntegerType, ArrayType
from pyspark.sql.utils import AnalysisException
from pyspark.sql import Row

import openai
from openai import OpenAI
import re
import ast

Requirement already satisfied: openai in /usr/local/lib/python3.11/dist-packages (1.81.0)
Collecting openai
  Downloading openai-1.82.0-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from openai) (4.9.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.10.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from openai) (2.11.4)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.11/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.11/dist-packages (from openai) (4.13.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (2025.4.26)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.1)
Downloading openai-1.82.0-py3-none-any.whl (720 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 720.4/720.4 kB 8.9 MB/s eta 0:00:00
Installing collected packages: openai
  Attempting uninstall: openai
    Found existing installation: openai 1.81.0
    Uninstalling openai-1.81.0:
      Successfully uninstalled openai-1.81.0
Successfully installed openai-1.82.0

### **Parameter setting**

PATHS

In [ ]:
# Path for storage
dtset_dir_csv = Path('/content/drive/MyDrive/Proyecto_RICORS/csv')
#dir_data = Path('/content/drive/MyDrive/Data Lake IONClinics/S2ORC completo/20240917/rawdata')
dtset_dir_parquet = Path('/content/drive/MyDrive/Proyecto_RICORS/Parquet')

### **Spark Session**

In [ ]:
!apt-get purge openjdk-* -y
!pip uninstall -y pyspark

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'openjdk-11-jdk' for glob 'openjdk-*'
Note, selecting 'openjdk-11-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-11-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-19-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-8-jre-zero' for glob 'openjdk-*'
Note, selecting 'openjdk-11-jdk-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-21-jdk-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-19-jdk-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-21-demo' for glob 'openjdk-*'
Note, selecting 'openjdk-18-jdk-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-17-dbg' for glob 'openjdk-*'
Note, selecting 'openjdk-17-doc' for glob 'openjdk-*'
Note, selecting 'openjdk-18-dbg' for glob 'openjdk-*'
Note, selecting 'openjdk-17-jdk' for glob 'openjdk-*'
Note, selecting 'openjdk-18-doc' for glob 'openjdk-*'
Note, selecting 'openjdk-17-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-17-jdk-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-19-dbg' for glob 'openjdk-*'
Note, selecting 'openjdk-18-jdk' for glob 'openjdk-*'
Note, selecting 'openjdk-19-doc' for glob 'openjdk-*'
Note, selecting 'openjdk-18-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-21-dbg' for glob 'openjdk-*'
Note, selecting 'openjdk-21-doc' for glob 'openjdk-*'
Note, selecting 'openjdk-19-jdk' for glob 'openjdk-*'
Note, selecting 'openjdk-19-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-21-jdk' for glob 'openjdk-*'
Note, selecting 'openjdk-21-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-19-source' for glob 'openjdk-*'
Note, selecting 'openjdk-11-demo' for glob 'openjdk-*'
Note, selecting 'openjdk-6-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-8-dbg' for glob 'openjdk-*'
Note, selecting 'openjdk-8-doc' for glob 'openjdk-*'
Note, selecting 'openjdk-7-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-21-testsupport' for glob 'openjdk-*'
Note, selecting 'openjdk-8-jdk' for glob 'openjdk-*'
Note, selecting 'openjdk-8-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-9-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-8-demo' for glob 'openjdk-*'
Note, selecting 'openjdk-8-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-8-source' for glob 'openjdk-*'
Note, selecting 'openjdk-19-jre-zero' for glob 'openjdk-*'
Note, selecting 'openjdk-17-source' for glob 'openjdk-*'
Note, selecting 'openjdk-17-demo' for glob 'openjdk-*'
Note, selecting 'openjdk-6-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-18-demo' for glob 'openjdk-*'
Note, selecting 'openjdk-11-source' for glob 'openjdk-*'
Note, selecting 'openjdk-19-demo' for glob 'openjdk-*'
Note, selecting 'openjdk-18-jre-zero' for glob 'openjdk-*'
Note, selecting 'openjdk-jre' for glob 'openjdk-*'
Note, selecting 'openjdk-11-jre-zero' for glob 'openjdk-*'
Note, selecting 'openjdk-21-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-8-jdk-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-21-source' for glob 'openjdk-*'
Note, selecting 'openjdk-14-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-18-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-17-jre-zero' for glob 'openjdk-*'
Note, selecting 'openjdk-13-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-17-jre-headless' for glob 'openjdk-*'
Note, selecting 'openjdk-18-source' for glob 'openjdk-*'
Note, selecting 'openjdk-11-dbg' for glob 'openjdk-*'
Note, selecting 'openjdk-11-doc' for glob 'openjdk-*'
Note, selecting 'openjdk-11-jre-dcevm' for glob 'openjdk-*'
Note, selecting 'openjdk-21-jre-zero' for glob 'openjdk-*'
Note, selecting 'openjdk-12-jre-headless' for glob 'openjdk-*'
Package 'openjdk-6-jre-headless' is not installed, so not removed
Package 'openjdk-14-jre-headless' is not installed, so not removed
Package 'openjdk-13-jre-headless' is not installed, so not removed
Package 'openjdk-12-jre-headless' is not installed, so not removed
Package 'openjdk-6-jre' is not installed, so not removed
Package 'openjdk-7-jre' is not installed, so not removed
Package 'openjdk-9-jre' is not installed, so not removed
Package 'openjdk-jre' is not installed, so not removed
Package 'openjdk-11-jre-dcevm' is not installed, so not removed
Package 'openjdk-11-dbg' is not installed, so not removed
Package 'openjdk-11-doc' is not installed, so not removed
Package 'openjdk-11-jdk' is not installed, so not removed
Package 'openjdk-11-jre' is not installed, so not removed
Package 'openjdk-11-source' is not installed, so not removed
Package 'openjdk-11-demo' is not installed, so not removed
Package 'openjdk-11-jre-zero' is not installed, so not removed
Package 'openjdk-17-dbg' is not installed, so not removed
Package 'openjdk-17-demo' is not installed, so not removed
Package 'openjdk-17-doc' is not installed, so not removed
Package 'openjdk-17-jdk' is not installed, so not removed
Package 'openjdk-17-jdk-headless' is not installed, so not removed
Package 'openjdk-17-jre' is not installed, so not removed
Package 'openjdk-17-jre-headless' is not installed, so not removed
Package 'openjdk-17-jre-zero' is not installed, so not removed
Package 'openjdk-17-source' is not installed, so not removed
Package 'openjdk-18-dbg' is not installed, so not removed
Package 'openjdk-18-demo' is not installed, so not removed
Package 'openjdk-18-doc' is not installed, so not removed
Package 'openjdk-18-jdk' is not installed, so not removed
Package 'openjdk-18-jdk-headless' is not installed, so not removed
Package 'openjdk-18-jre' is not installed, so not removed
Package 'openjdk-18-jre-headless' is not installed, so not removed
Package 'openjdk-18-jre-zero' is not installed, so not removed
Package 'openjdk-18-source' is not installed, so not removed
Package 'openjdk-19-dbg' is not installed, so not removed
Package 'openjdk-19-demo' is not installed, so not removed
Package 'openjdk-19-doc' is not installed, so not removed
Package 'openjdk-19-jdk' is not installed, so not removed
Package 'openjdk-19-jdk-headless' is not installed, so not removed
Package 'openjdk-19-jre' is not installed, so not removed
Package 'openjdk-19-jre-headless' is not installed, so not removed
Package 'openjdk-19-jre-zero' is not installed, so not removed
Package 'openjdk-19-source' is not installed, so not removed
Package 'openjdk-21-dbg' is not installed, so not removed
Package 'openjdk-21-demo' is not installed, so not removed
Package 'openjdk-21-doc' is not installed, so not removed
Package 'openjdk-21-jdk' is not installed, so not removed
Package 'openjdk-21-jdk-headless' is not installed, so not removed
Package 'openjdk-21-jre' is not installed, so not removed
Package 'openjdk-21-jre-headless' is not installed, so not removed
Package 'openjdk-21-jre-zero' is not installed, so not removed
Package 'openjdk-21-source' is not installed, so not removed
Package 'openjdk-21-testsupport' is not installed, so not removed
Package 'openjdk-8-dbg' is not installed, so not removed
Package 'openjdk-8-demo' is not installed, so not removed
Package 'openjdk-8-doc' is not installed, so not removed
Package 'openjdk-8-jdk' is not installed, so not removed
Package 'openjdk-8-jdk-headless' is not installed, so not removed
Package 'openjdk-8-jre' is not installed, so not removed
Package 'openjdk-8-jre-headless' is not installed, so not removed
Package 'openjdk-8-jre-zero' is not installed, so not removed
Package 'openjdk-8-source' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  java-common libpcsclite1
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  ca-certificates-java* openjdk-11-jdk-headless* openjdk-11-jre-headless*
0 upgraded, 0 newly installed, 3 to remove and 35 not upgraded.
After this operation, 258 MB disk space will be freed.
(Reading database ... 126109 files and directories currently installed.)
Removing openjdk-11-jdk-headless:amd64 (11.0.27+6~us1-0ubuntu1~22.04) ...
Removing openjdk-11-jre-headless:amd64 (11.0.27+6~us1-0ubuntu1~22.04) ...
Removing ca-certificates-java (20190909ubuntu1.2) ...
Processing triggers for ca-certificates (20240203~22.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

updates of cacerts keystore disabled.
done.
(Reading database ... 125650 files and directories currently installed.)
Purging configuration files for openjdk-11-jre-headless:amd64 (11.0.27+6~us1-0ubuntu1~22.04) ...
Purging configuration files for ca-certificates-java (20190909ubuntu1.2) ...
Found existing installation: pyspark 3.5.1
Uninstalling pyspark-3.5.1:
  Successfully uninstalled pyspark-3.5.1

In [ ]:
!apt-get update -y
!apt-get install -y openjdk-11-jdk-headless

Get:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [1,702 kB]
Get:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:12 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [8,968 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [2,951 kB]
Get:14 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [34.3 kB]
Get:15 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,728 kB]
Get:16 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [4,402 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [4,564 kB]
Get:18 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,245 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [3,264 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,552 kB]
Fetched 31.8 MB in 5s (6,409 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  ca-certificates-java openjdk-11-jre-headless
Suggested packages:
  openjdk-11-demo openjdk-11-source libnss-mdns fonts-dejavu-extra
  fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei
  | fonts-wqy-zenhei fonts-indic
The following NEW packages will be installed:
  ca-certificates-java openjdk-11-jdk-headless openjdk-11-jre-headless
0 upgraded, 3 newly installed, 0 to remove and 47 not upgraded.
Need to get 116 MB of archives.
After this operation, 258 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jre-headless amd64 11.0.27+6~us1-0ubuntu1~22.04 [42.6 MB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 ca-certificates-java all 20190909ubuntu1.2 [12.1 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 openjdk-11-jdk-headless amd64 11.0.27+6~us1-0ubuntu1~22.04 [73.6 MB]
Fetched 116 MB in 4s (27.0 MB/s)
Selecting previously unselected package openjdk-11-jre-headless:amd64.
(Reading database ... 125616 files and directories currently installed.)
Preparing to unpack .../openjdk-11-jre-headless_11.0.27+6~us1-0ubuntu1~22.04_amd64.deb ...
Unpacking openjdk-11-jre-headless:amd64 (11.0.27+6~us1-0ubuntu1~22.04) ...
Selecting previously unselected package ca-certificates-java.
Preparing to unpack .../ca-certificates-java_20190909ubuntu1.2_all.deb ...
Unpacking ca-certificates-java (20190909ubuntu1.2) ...
Selecting previously unselected package openjdk-11-jdk-headless:amd64.
Preparing to unpack .../openjdk-11-jdk-headless_11.0.27+6~us1-0ubuntu1~22.04_amd64.deb ...
Unpacking openjdk-11-jdk-headless:amd64 (11.0.27+6~us1-0ubuntu1~22.04) ...
Setting up ca-certificates-java (20190909ubuntu1.2) ...
head: cannot open '/etc/ssl/certs/java/cacerts' for reading: No such file or directory
Adding debian:QuoVadis_Root_CA_1_G3.pem
Adding debian:SwissSign_Gold_CA_-_G2.pem
Adding debian:NetLock_Arany_=Class_Gold=_Főtanúsítvány.pem
Adding debian:Certigna.pem
Adding debian:GlobalSign_Root_R46.pem
Adding debian:AffirmTrust_Premium_ECC.pem
Adding debian:Entrust_Root_Certification_Authority.pem
Adding debian:TWCA_Root_Certification_Authority.pem
Adding debian:QuoVadis_Root_CA_3_G3.pem
Adding debian:QuoVadis_Root_CA_2_G3.pem
Adding debian:SSL.com_Root_Certification_Authority_RSA.pem
Adding debian:emSign_Root_CA_-_C1.pem
Adding debian:Trustwave_Global_Certification_Authority.pem
Adding debian:vTrus_ECC_Root_CA.pem
Adding debian:GTS_Root_R3.pem
Adding debian:OISTE_WISeKey_Global_Root_GB_CA.pem
Adding debian:AC_RAIZ_FNMT-RCM.pem
Adding debian:QuoVadis_Root_CA_2.pem
Adding debian:Security_Communication_RootCA2.pem
Adding debian:CFCA_EV_ROOT.pem
Adding debian:Starfield_Class_2_CA.pem
Adding debian:OISTE_WISeKey_Global_Root_GC_CA.pem
Adding debian:Entrust_Root_Certification_Authority_-_G4.pem
Adding debian:Security_Communication_ECC_RootCA1.pem
Adding debian:USERTrust_ECC_Certification_Authority.pem
Adding debian:Hellenic_Academic_and_Research_Institutions_RootCA_2015.pem
Adding debian:D-TRUST_Root_Class_3_CA_2_EV_2009.pem
Adding debian:Starfield_Root_Certificate_Authority_-_G2.pem
Adding debian:Izenpe.com.pem
Adding debian:Entrust_Root_Certification_Authority_-_EC1.pem
Adding debian:DigiCert_Global_Root_CA.pem
Adding debian:GlobalSign_Root_CA.pem
Adding debian:Starfield_Services_Root_Certificate_Authority_-_G2.pem
Adding debian:GlobalSign_ECC_Root_CA_-_R5.pem
Adding debian:Buypass_Class_2_Root_CA.pem
Adding debian:Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068.pem
Adding debian:DigiCert_Global_Root_G2.pem
Adding debian:Microsoft_RSA_Root_Certificate_Authority_2017.pem
Adding debian:Certainly_Root_R1.pem
Adding debian:ANF_Secure_Server_Root_CA.pem
Adding debian:D-TRUST_Root_Class_3_CA_2_2009.pem
Adding debian:DigiCert_TLS_ECC_P384_Root_G5.pem
Adding debian:SSL.com_Root_Certification_Authority_ECC.pem
Adding debian:DigiCert_Assured_ID_Root_G3.pem
Adding debian:D-TRUST_BR_Root_CA_1_2020.pem
Adding debian:HARICA_TLS_RSA_Root_CA_2021.pem
Adding debian:GDCA_TrustAUTH_R5_ROOT.pem
Adding debian:AffirmTrust_Networking.pem
Adding debian:Certum_Trusted_Network_CA_2.pem
Adding debian:GLOBALTRUST_2020.pem
Adding debian:AffirmTrust_Premium.pem
Adding debian:Amazon_Root_CA_1.pem
Adding debian:Security_Communication_Root_CA.pem
Adding debian:vTrus_Root_CA.pem
Adding debian:e-Szigno_Root_CA_2017.pem
Adding debian:Secure_Global_CA.pem
Adding debian:TUBITAK_Kamu_SM_SSL_Kok_Sertifikasi_-_Surum_1.pem
Adding debian:T-TeleSec_GlobalRoot_Class_3.pem
Adding debian:SecureTrust_CA.pem
Adding debian:Trustwave_Global_ECC_P384_Certification_Authority.pem
Adding debian:ISRG_Root_X2.pem
Adding debian:HARICA_TLS_ECC_Root_CA_2021.pem
Adding debian:COMODO_Certification_Authority.pem
Adding debian:Security_Communication_RootCA3.pem
Adding debian:Microsoft_ECC_Root_Certificate_Authority_2017.pem
Adding debian:USERTrust_RSA_Certification_Authority.pem
Adding debian:COMODO_ECC_Certification_Authority.pem
Adding debian:GlobalSign_Root_CA_-_R6.pem
Adding debian:UCA_Global_G2_Root.pem
Adding debian:DigiCert_Trusted_Root_G4.pem
Adding debian:Amazon_Root_CA_4.pem
Adding debian:emSign_Root_CA_-_G1.pem
Adding debian:SwissSign_Silver_CA_-_G2.pem
Adding debian:emSign_ECC_Root_CA_-_C3.pem
Adding debian:GlobalSign_Root_CA_-_R3.pem
Adding debian:CA_Disig_Root_R2.pem
Adding debian:Baltimore_CyberTrust_Root.pem
Adding debian:Go_Daddy_Root_Certificate_Authority_-_G2.pem
Adding debian:Telia_Root_CA_v2.pem
Adding debian:SSL.com_EV_Root_Certification_Authority_ECC.pem
Adding debian:Hongkong_Post_Root_CA_3.pem
Adding debian:GlobalSign_ECC_Root_CA_-_R4.pem
Adding debian:DigiCert_Global_Root_G3.pem
Adding debian:ePKI_Root_Certification_Authority.pem
Adding debian:Entrust.net_Premium_2048_Secure_Server_CA.pem
Adding debian:D-TRUST_EV_Root_CA_1_2020.pem
Adding debian:AffirmTrust_Commercial.pem
Adding debian:DigiCert_High_Assurance_EV_Root_CA.pem
Adding debian:Certigna_Root_CA.pem
Adding debian:AC_RAIZ_FNMT-RCM_SERVIDORES_SEGUROS.pem
Adding debian:Amazon_Root_CA_2.pem
Adding debian:NAVER_Global_Root_Certification_Authority.pem
Adding debian:Go_Daddy_Class_2_CA.pem
Adding debian:UCA_Extended_Validation_Root.pem
Adding debian:GlobalSign_Root_E46.pem
Adding debian:ACCVRAIZ1.pem
Adding debian:emSign_ECC_Root_CA_-_G3.pem
Adding debian:T-TeleSec_GlobalRoot_Class_2.pem
Adding debian:TunTrust_Root_CA.pem
Adding debian:GTS_Root_R4.pem
Adding debian:DigiCert_TLS_RSA4096_Root_G5.pem
Adding debian:certSIGN_ROOT_CA.pem
Adding debian:IdenTrust_Commercial_Root_CA_1.pem
Adding debian:Microsec_e-Szigno_Root_CA_2009.pem
Adding debian:DigiCert_Assured_ID_Root_CA.pem
Adding debian:QuoVadis_Root_CA_3.pem
Adding debian:Certum_Trusted_Network_CA.pem
Adding debian:IdenTrust_Public_Sector_Root_CA_1.pem
Adding debian:Amazon_Root_CA_3.pem
Adding debian:TeliaSonera_Root_CA_v1.pem
Adding debian:SZAFIR_ROOT_CA2.pem
Adding debian:SSL.com_EV_Root_Certification_Authority_RSA_R2.pem
Adding debian:SecureSign_RootCA11.pem
Adding debian:HiPKI_Root_CA_-_G1.pem
Adding debian:COMODO_RSA_Certification_Authority.pem
Adding debian:Entrust_Root_Certification_Authority_-_G2.pem
Adding debian:DigiCert_Assured_ID_Root_G2.pem
Adding debian:TWCA_Global_Root_CA.pem
Adding debian:Certum_Trusted_Root_CA.pem
Adding debian:ISRG_Root_X1.pem
Adding debian:Trustwave_Global_ECC_P256_Certification_Authority.pem
Adding debian:certSIGN_Root_CA_G2.pem
Adding debian:XRamp_Global_CA_Root.pem
Adding debian:GTS_Root_R1.pem
Adding debian:Buypass_Class_3_Root_CA.pem
Adding debian:Certainly_Root_E1.pem
Adding debian:Actalis_Authentication_Root_CA.pem
Adding debian:Certum_EC-384_CA.pem
Adding debian:Comodo_AAA_Services_root.pem
Adding debian:GTS_Root_R2.pem
Adding debian:Hellenic_Academic_and_Research_Institutions_ECC_RootCA_2015.pem
Adding debian:Atos_TrustedRoot_2011.pem
Adding debian:TrustAsia_Global_Root_CA_G3.pem
Adding debian:Atos_TrustedRoot_Root_CA_ECC_TLS_2021.pem
Adding debian:TrustAsia_Global_Root_CA_G4.pem
Adding debian:Sectigo_Public_Server_Authentication_Root_R46.pem
Adding debian:SSL.com_TLS_RSA_Root_CA_2022.pem
Adding debian:BJCA_Global_Root_CA1.pem
Adding debian:CommScope_Public_Trust_RSA_Root-02.pem
Adding debian:CommScope_Public_Trust_RSA_Root-01.pem
Adding debian:SSL.com_TLS_ECC_Root_CA_2022.pem
Adding debian:BJCA_Global_Root_CA2.pem
Adding debian:Atos_TrustedRoot_Root_CA_RSA_TLS_2021.pem
Adding debian:Sectigo_Public_Server_Authentication_Root_E46.pem
Adding debian:CommScope_Public_Trust_ECC_Root-01.pem
Adding debian:CommScope_Public_Trust_ECC_Root-02.pem
done.
Processing triggers for ca-certificates (20240203~22.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...

done.
done.
Setting up openjdk-11-jre-headless:amd64 (11.0.27+6~us1-0ubuntu1~22.04) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/java to provide /usr/bin/java (java) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jjs to provide /usr/bin/jjs (jjs) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/unpack200 to provide /usr/bin/unpack200 (unpack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode
Setting up openjdk-11-jdk-headless:amd64 (11.0.27+6~us1-0ubuntu1~22.04) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jar to provide /usr/bin/jar (jar) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jarsigner to provide /usr/bin/jarsigner (jarsigner) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/javac to provide /usr/bin/javac (javac) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/javadoc to provide /usr/bin/javadoc (javadoc) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/javap to provide /usr/bin/javap (javap) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jcmd to provide /usr/bin/jcmd (jcmd) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jdb to provide /usr/bin/jdb (jdb) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jdeprscan to provide /usr/bin/jdeprscan (jdeprscan) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jdeps to provide /usr/bin/jdeps (jdeps) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jfr to provide /usr/bin/jfr (jfr) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jimage to provide /usr/bin/jimage (jimage) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jinfo to provide /usr/bin/jinfo (jinfo) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jlink to provide /usr/bin/jlink (jlink) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jmap to provide /usr/bin/jmap (jmap) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jmod to provide /usr/bin/jmod (jmod) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jps to provide /usr/bin/jps (jps) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jrunscript to provide /usr/bin/jrunscript (jrunscript) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jshell to provide /usr/bin/jshell (jshell) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jstack to provide /usr/bin/jstack (jstack) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jstat to provide /usr/bin/jstat (jstat) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jstatd to provide /usr/bin/jstatd (jstatd) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmic to provide /usr/bin/rmic (rmic) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/serialver to provide /usr/bin/serialver (serialver) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jaotc to provide /usr/bin/jaotc (jaotc) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jhsdb to provide /usr/bin/jhsdb (jhsdb) in auto mode

In [ ]:
import os

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["PATH"] = os.environ["JAVA_HOME"] + "/bin:" + os.environ["PATH"]

!echo $JAVA_HOME
!java -version

/usr/lib/jvm/java-11-openjdk-amd64
openjdk version "11.0.27" 2025-04-15
OpenJDK Runtime Environment (build 11.0.27+6-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.27+6-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

In [ ]:
!pip install pyspark==3.5.1

Collecting pyspark==3.5.1
  Downloading pyspark-3.5.1.tar.gz (317.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.0/317.0 MB 4.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.11/dist-packages (from pyspark==3.5.1) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.1-py2.py3-none-any.whl size=317488493 sha256=15c89f06b72fed167ab2300b6b3d816326f695c9ded633c513d080fb2025c13e
  Stored in directory: /root/.cache/pip/wheels/95/13/41/f7f135ee114175605fb4f0a89e7389f3742aa6c1e1a5bcb657
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-3.5.1

In [ ]:
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .master("local[*]") \
    .appName("pregnancy_hypertension") \
    .config("spark.driver.memory", "4g") \
    .config("spark.executor.memory", "4g") \
    .getOrCreate()

In [ ]:
rdd = spark.sparkContext.parallelize(range(100))
print("Spark partitions:", rdd.getNumPartitions())

Spark partitions: 2

In [ ]:
spark

In [ ]:
dtset_dir_parquet = Path(dtset_dir_parquet)
fs = spark._jvm.org.apache.hadoop.fs.FileSystem.get(spark._jsc.hadoopConfiguration())
hdfs_dir_parquet = spark._jvm.org.apache.hadoop.fs.Path(dtset_dir_parquet.as_posix())
if not fs.exists(hdfs_dir_parquet):
    fs.mkdirs(hdfs_dir_parquet)

## **Antihypertensive Literature Retriever**

### **Extracción de documentos relacionados con embarazo**

En este proceso se depura y filtra el corpus inicial para identificar únicamente los textos relevantes para embarazo. Las acciones principales incluyen:

1. **Eliminar las secciones de agradecimientos y referencias** del texto, con el fin de conservar únicamente el contenido científico relevante.

2. **Filtrar los artículos que contienen la palabra clave 'pregnancy'**, asegurando que solo se analicen documentos directamente relacionados con esta técnica.

In [ ]:
## SUGERENCIA GPT para filtrado más relevante

from pyspark.sql.functions import udf, col
from pyspark.sql.types import IntegerType

def filter_kw_distinct_match(dataframe, text_column, keyword_list, thr):
    def count_distinct_matches(text):
        if text is None:
            return 0
        text = text.lower()
        return sum(1 for kw in keyword_list if kw.lower() in text)

    count_udf = udf(count_distinct_matches, IntegerType())
    dataset = dataframe.withColumn("Kwd_count", count_udf(col(text_column)))
    dataset = dataset.filter(col("Kwd_count") >= thr).cache()

    return dataset

In [ ]:
## Filtrado original
def filter_kw(dataframe, text_column, keyword_list,thr):
    def count_kwds(text):
        if text is None:
            return 0
        else:
            return sum(text.lower().count(k) for k in keyword_list)

    count_kwds_udf = udf(count_kwds, IntegerType())
    dataset = dataframe.withColumn("Kwd_count", count_kwds_udf(dataframe[text_column]))
    dataset = dataset.filter(dataset.Kwd_count > thr).cache()

    return dataset

In [ ]:
def filter_acknowledgements(df, text_column):  ## Remove acknowledgments and reference section from text
    df = df.withColumn(text_column, regexp_replace(df[text_column], '\n', ' '))
    df_filtered = df.withColumn(
        text_column,
        expr("CASE \
             WHEN INSTR(lower({}), 'acknowledgments') > 0 THEN substring_index(lower({}), 'acknowledgments', 1) \
             WHEN INSTR(lower({}), 'conflicts of interest') > 0 THEN substring_index(lower({}), 'conflicts of interest', 1) \
             WHEN INSTR(lower({}), '[crossref]') > 0 THEN substring_index(lower({}), '[crossref]', 1) \
             WHEN INSTR(lower({}), '10.') > 0 THEN substring_index(lower({}), '10.', 3) \
             ELSE {} END".format(text_column, text_column, text_column, text_column, text_column,text_column, text_column, text_column, text_column ))
    )
    return df_filtered

In [ ]:
def extract_text(dir_papers, keywords):  ##  def extract_text(dir_papers, x) -- Use this if you want to filter by batches
    df_text_filtered_concat = None

    try:
        # Get a list of the JSON files in the directory
        json_files = sorted(dir_papers.glob('*.json.gz')) #[:x]  -- Use this if you want to filter by batches

        for json_file in json_files:
            try:
                df = spark.read.json('file:///' + json_file.as_posix())
                print(f'Reading data from {json_file.name}')

                # Select relevant columns
                df_text = df.select('corpusid', col('content.text').alias('text'))

                # Filter by acknowledgements and keyword threshold
                df_text_acknow = filter_acknowledgements(df_text, 'text') # Filter by acknowledgements
                df_text_abstract_filter_tdcs = filter_kw(df_text_acknow, 'text', keywords,10) # Filter by keyword
                #df_text_filtered = filter_kw_distinct_match(df_text_acknow, 'text', keywords, 1) # Filtro más estricto para mayor relevancia


                # Concatenate with the previous filtered dataframe
                if df_text_filtered_concat is not None:
                    df_text_filtered_concat = df_text_filtered_concat.union(df_text_abstract_filter_tdcs)
                else:
                    df_text_filtered_concat = df_text_abstract_filter_tdcs

            except AnalysisException as e:
                print(f'Error reading data from {json_file.name}: {e}')

    except Exception as e:
        print(f'Unexpected error: {e}')

    return df_text_filtered_concat

In [ ]:
# Last Version
dir_data = Path('/content/drive/MyDrive/Proyecto_tDCS/Data Lake IONClinics/S2ORC completo/20240917/rawdata')
dir_papers = dir_data.joinpath('s2orc')
keywords = ["pregnancy", "pregnant", "gestational", "antenatal"]
df_papers_pregnancy = extract_text(dir_papers,keywords)

if df_papers_pregnancy:
    print('Number of documents in dataset:', df_papers_pregnancy.count())
    df_papers_pregnancy.show(n=15, truncate=300, vertical=True)
else:
    print("No documents found after filtering.")

Reading data from s2orc-part0.json.gz
Reading data from s2orc-part1.json.gz
Unexpected error: An error occurred while calling o717.json.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 80.0 failed 1 times, most recent failure: Lost task 0.0 in stage 80.0 (TID 87) (d375b2acf679 executor driver): java.io.EOFException: Unexpected end of input stream
	at org.apache.hadoop.io.compress.DecompressorStream.decompress(DecompressorStream.java:165)
	at org.apache.hadoop.io.compress.DecompressorStream.read(DecompressorStream.java:105)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at org.apache.hadoop.util.LineReader.fillBuffer(LineReader.java:191)
	at org.apache.hadoop.util.LineReader.readDefaultLine(LineReader.java:227)
	at org.apache.hadoop.util.LineReader.readLine(LineReader.java:185)
	at org.apache.hadoop.mapreduce.lib.input.LineRecordReader.nextKeyValue(LineRecordReader.java:200)
	at org.apache.spark.sql.execution.datasources.RecordReaderIterator.hasNext(RecordReaderIterator.scala:39)
	at org.apache.spark.sql.execution.datasources.HadoopFileLinesReader.hasNext(HadoopFileLinesReader.scala:67)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:129)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.TraversableOnce.reduceLeft(TraversableOnce.scala:237)
	at scala.collection.TraversableOnce.reduceLeft$(TraversableOnce.scala:220)
	at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1431)
	at scala.collection.TraversableOnce.reduceLeftOption(TraversableOnce.scala:249)
	at scala.collection.TraversableOnce.reduceLeftOption$(TraversableOnce.scala:248)
	at scala.collection.AbstractIterator.reduceLeftOption(Iterator.scala:1431)
	at scala.collection.TraversableOnce.reduceOption(TraversableOnce.scala:256)
	at scala.collection.TraversableOnce.reduceOption$(TraversableOnce.scala:256)
	at scala.collection.AbstractIterator.reduceOption(Iterator.scala:1431)
	at org.apache.spark.sql.catalyst.json.JsonInferSchema.$anonfun$infer$1(JsonInferSchema.scala:107)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:858)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:858)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2398)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2493)
	at org.apache.spark.sql.catalyst.json.JsonInferSchema.infer(JsonInferSchema.scala:120)
	at org.apache.spark.sql.execution.datasources.json.TextInputJsonDataSource$.$anonfun$inferFromDataset$5(JsonDataSource.scala:109)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.datasources.json.TextInputJsonDataSource$.inferFromDataset(JsonDataSource.scala:109)
	at org.apache.spark.sql.execution.datasources.json.TextInputJsonDataSource$.infer(JsonDataSource.scala:98)
	at org.apache.spark.sql.execution.datasources.json.JsonDataSource.inferSchema(JsonDataSource.scala:64)
	at org.apache.spark.sql.execution.datasources.json.JsonFileFormat.inferSchema(JsonFileFormat.scala:59)
	at org.apache.spark.sql.execution.datasources.DataSource.$anonfun$getOrInferFileFormatSchema$11(DataSource.scala:208)
	at scala.Option.orElse(Option.scala:447)
	at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:205)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:407)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:362)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.EOFException: Unexpected end of input stream
	at org.apache.hadoop.io.compress.DecompressorStream.decompress(DecompressorStream.java:165)
	at org.apache.hadoop.io.compress.DecompressorStream.read(DecompressorStream.java:105)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at org.apache.hadoop.util.LineReader.fillBuffer(LineReader.java:191)
	at org.apache.hadoop.util.LineReader.readDefaultLine(LineReader.java:227)
	at org.apache.hadoop.util.LineReader.readLine(LineReader.java:185)
	at org.apache.hadoop.mapreduce.lib.input.LineRecordReader.nextKeyValue(LineRecordReader.java:200)
	at org.apache.spark.sql.execution.datasources.RecordReaderIterator.hasNext(RecordReaderIterator.scala:39)
	at org.apache.spark.sql.execution.datasources.HadoopFileLinesReader.hasNext(HadoopFileLinesReader.scala:67)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:129)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.TraversableOnce.reduceLeft(TraversableOnce.scala:237)
	at scala.collection.TraversableOnce.reduceLeft$(TraversableOnce.scala:220)
	at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1431)
	at scala.collection.TraversableOnce.reduceLeftOption(TraversableOnce.scala:249)
	at scala.collection.TraversableOnce.reduceLeftOption$(TraversableOnce.scala:248)
	at scala.collection.AbstractIterator.reduceLeftOption(Iterator.scala:1431)
	at scala.collection.TraversableOnce.reduceOption(TraversableOnce.scala:256)
	at scala.collection.TraversableOnce.reduceOption$(TraversableOnce.scala:256)
	at scala.collection.AbstractIterator.reduceOption(Iterator.scala:1431)
	at org.apache.spark.sql.catalyst.json.JsonInferSchema.$anonfun$infer$1(JsonInferSchema.scala:107)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:858)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:858)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more

Number of documents in dataset: 1239
-RECORD 0-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 220670724
 text      |  original article is placental kiss-1 expression associated with first trimester abortion spontaneous? 2020  mdeser colak dresercolak@hotmail.com  mdemel ebru ozcimen  hilal ozgur  mderinanç  mdyusuf aytac tohma  department of gynecology and obstetrics department of gynecology and obstetrics, kon...
 Kwd_count | 59
-RECORD 1-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 259345407
 text      |  mental health, sleep quality, and hormonal circadian rhythms in pregnant women with threatened preterm labor: a prospective observational study   xiao-juan wang  xiao-ting li  na chen  long huang  shui-xiu huang  ting-ting chen  gui-hua liu  rong-fang hu hurongfang1234@sina.com  gui-hua liu  ron...
 Kwd_count | 60
-RECORD 2-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 53874492
 text      |  characterization of maternal plasma biomarkers associated with delivery of small and large for gestational age infants in the mirec study cohort published: november 1, 2018  premkumari kumarathasan id *premkumari.kumarathasan@hc-sc.gc.ca  environmental health science and research bureau healthy ...
 Kwd_count | 74
-RECORD 3-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 246165778
 text      |  long term miscarriage-related hypertension and diabetes mellitus. evidence from a united kingdom population-based cohort study   kelvin okoth id  institute of applied health research university of birmingham birminghamunited kingdom  anuradhaa subramanian  institute of applied health research un...
 Kwd_count | 20
-RECORD 4-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 4901995
 text      |  case report in vitro fertilization using luteinizing hormone-releasing hormone injections resulted in healthy triplets without increased attack rates in a hereditary angioedema case published 13 february 2018  ceyda tunakan dalgjç  department of internal medicine division of allergy and clinical...
 Kwd_count | 29
-RECORD 5-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 268424763
 text      |   14 march 2024  mdcindy m martin cmmartin2@houstonmethodist.org  houston methodist debakey heart & vascular center houstontexas, us  houston methodist debakey heart & vascular center houstontexas, us 14 march 202496ee25448631b3b0dec6415cce08145d10.14797/mdcvj.1368submitted: 15 february 2024 acce...
 Kwd_count | 19
-RECORD 6-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 256223001
 text      |  burden and trend of macrosomia and large-for-gestational-age neonates attributable to high pre-pregnancy body mass index in china, 2013-2017: a population-based retrospective cohort study   warren ruktanonchai  shuai zeng  institute of epidemiology and statistics school of public health lanzhou ...
 Kwd_count | 61
-RECORD 7-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 231939770
 text      |  effect of overweight/obesity on caesarean section occurrence among reproductive-aged women in ethiopia: a secondary data analysis 2021. 2021  melese linger endalifer  department of public health melese linger endalifer college of health science woldia university woldiaethiopia  gedefaw diress  d...
 Kwd_count | 11
-RECORD 8-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 199037976
 text      |  clinical course in a patient with myopathic vlcad deficiency during pregnancy with an affected baby   kenji yamada k-yamada@med.shimane-u.ac.jp  department of pediatrics faculty of medicine shimane university izumo, shimanejapan  keiichi matsubara  department of obstetrics and gynecology ehime u...
 Kwd_count | 27
-RECORD 9-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 42468435
 text      |  detection of anti-cmv igm and anti-toxoplasma gondii igg in pregnant women with history of abortion   saeed kholam  department of medical microbiology college of medicine hawler medical university erbiliraq  zagros kamal al-barzanjy  department of medical microbiology college of medicine hawler ...
 Kwd_count | 28
-RECORD 10----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 248985910
 text      |  evaluating the effect of bolsa familia, brazil's conditional cash transfer programme, on maternal and child health: a study protocol   ila rocha  falcão id  school of nutrition federal university of bahia salvadorbrazil  centre for data and knowledge integration for health (cidacs) oswaldo cruz ...
 Kwd_count | 57
-RECORD 11----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 51698536
 text      |    326 DR J. M. DUNCAN ON THE THEORY OF   Since the time of the Hunters, physiologists have taught that one of the earliest results of successful impregnation, is the formation or deposition of a new membrane in the cavity of the uterus. This membrane, the caduca of Harvey, and to which William H...
 Kwd_count | 13
-RECORD 12----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 4840210
 text      |  social ecological factors and intimate partner violence in pregnancy   bosena tebeje gashaw  college of health sciences jimma university jimmaethiopia  faculty of medicine university of oslo oslo, norway  berit schei  department of public health and nursing faculty of medicine and health science...
 Kwd_count | 75
-RECORD 13----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 80628495

In [ ]:
# Primer intento solo con 'Pregnancy'
## Colocar path de acuerdo al release id especifico de cuando hizo la descarga
## Por ejemplo --> dir_data = Path('/content/drive/MyDrive/Data Lake IONClinics/S2ORC completo/20240917/rawdata')

dir_data = Path('/content/drive/MyDrive/Proyecto_tDCS/Data Lake IONClinics/S2ORC completo/20240917/rawdata')
dir_papers = dir_data.joinpath('s2orc')
df_papers_pregnancy = extract_text(dir_papers)

if df_papers_pregnancy:
    print('Number of documents in dataset:', df_papers_pregnancy.count())
    df_papers_pregnancy.show(n=15, truncate=300, vertical=True)
else:
    print("No documents found after filtering.")

Reading data from s2orc-part0.json.gz
Reading data from s2orc-part1.json.gz
Unexpected error: An error occurred while calling o117.json.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 1 times, most recent failure: Lost task 0.0 in stage 2.0 (TID 2) (c13b1c24173c executor driver): java.io.EOFException: Unexpected end of input stream
	at org.apache.hadoop.io.compress.DecompressorStream.decompress(DecompressorStream.java:165)
	at org.apache.hadoop.io.compress.DecompressorStream.read(DecompressorStream.java:105)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at org.apache.hadoop.util.LineReader.fillBuffer(LineReader.java:191)
	at org.apache.hadoop.util.LineReader.readDefaultLine(LineReader.java:227)
	at org.apache.hadoop.util.LineReader.readLine(LineReader.java:185)
	at org.apache.hadoop.mapreduce.lib.input.LineRecordReader.nextKeyValue(LineRecordReader.java:200)
	at org.apache.spark.sql.execution.datasources.RecordReaderIterator.hasNext(RecordReaderIterator.scala:39)
	at org.apache.spark.sql.execution.datasources.HadoopFileLinesReader.hasNext(HadoopFileLinesReader.scala:67)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:129)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.TraversableOnce.reduceLeft(TraversableOnce.scala:237)
	at scala.collection.TraversableOnce.reduceLeft$(TraversableOnce.scala:220)
	at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1431)
	at scala.collection.TraversableOnce.reduceLeftOption(TraversableOnce.scala:249)
	at scala.collection.TraversableOnce.reduceLeftOption$(TraversableOnce.scala:248)
	at scala.collection.AbstractIterator.reduceLeftOption(Iterator.scala:1431)
	at scala.collection.TraversableOnce.reduceOption(TraversableOnce.scala:256)
	at scala.collection.TraversableOnce.reduceOption$(TraversableOnce.scala:256)
	at scala.collection.AbstractIterator.reduceOption(Iterator.scala:1431)
	at org.apache.spark.sql.catalyst.json.JsonInferSchema.$anonfun$infer$1(JsonInferSchema.scala:107)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:858)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:858)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2398)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2493)
	at org.apache.spark.sql.catalyst.json.JsonInferSchema.infer(JsonInferSchema.scala:120)
	at org.apache.spark.sql.execution.datasources.json.TextInputJsonDataSource$.$anonfun$inferFromDataset$5(JsonDataSource.scala:109)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.datasources.json.TextInputJsonDataSource$.inferFromDataset(JsonDataSource.scala:109)
	at org.apache.spark.sql.execution.datasources.json.TextInputJsonDataSource$.infer(JsonDataSource.scala:98)
	at org.apache.spark.sql.execution.datasources.json.JsonDataSource.inferSchema(JsonDataSource.scala:64)
	at org.apache.spark.sql.execution.datasources.json.JsonFileFormat.inferSchema(JsonFileFormat.scala:59)
	at org.apache.spark.sql.execution.datasources.DataSource.$anonfun$getOrInferFileFormatSchema$11(DataSource.scala:208)
	at scala.Option.orElse(Option.scala:447)
	at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:205)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:407)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:362)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.EOFException: Unexpected end of input stream
	at org.apache.hadoop.io.compress.DecompressorStream.decompress(DecompressorStream.java:165)
	at org.apache.hadoop.io.compress.DecompressorStream.read(DecompressorStream.java:105)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at org.apache.hadoop.util.LineReader.fillBuffer(LineReader.java:191)
	at org.apache.hadoop.util.LineReader.readDefaultLine(LineReader.java:227)
	at org.apache.hadoop.util.LineReader.readLine(LineReader.java:185)
	at org.apache.hadoop.mapreduce.lib.input.LineRecordReader.nextKeyValue(LineRecordReader.java:200)
	at org.apache.spark.sql.execution.datasources.RecordReaderIterator.hasNext(RecordReaderIterator.scala:39)
	at org.apache.spark.sql.execution.datasources.HadoopFileLinesReader.hasNext(HadoopFileLinesReader.scala:67)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:129)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.TraversableOnce.reduceLeft(TraversableOnce.scala:237)
	at scala.collection.TraversableOnce.reduceLeft$(TraversableOnce.scala:220)
	at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1431)
	at scala.collection.TraversableOnce.reduceLeftOption(TraversableOnce.scala:249)
	at scala.collection.TraversableOnce.reduceLeftOption$(TraversableOnce.scala:248)
	at scala.collection.AbstractIterator.reduceLeftOption(Iterator.scala:1431)
	at scala.collection.TraversableOnce.reduceOption(TraversableOnce.scala:256)
	at scala.collection.TraversableOnce.reduceOption$(TraversableOnce.scala:256)
	at scala.collection.AbstractIterator.reduceOption(Iterator.scala:1431)
	at org.apache.spark.sql.catalyst.json.JsonInferSchema.$anonfun$infer$1(JsonInferSchema.scala:107)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2(RDD.scala:858)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitions$2$adapted(RDD.scala:858)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
	at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
	at org.apache.spark.scheduler.Task.run(Task.scala:141)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
	at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more

Number of documents in dataset: 810
-RECORD 0-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 220670724
 text      |  original article is placental kiss-1 expression associated with first trimester abortion spontaneous? 2020  mdeser colak dresercolak@hotmail.com  mdemel ebru ozcimen  hilal ozgur  mderinanç  mdyusuf aytac tohma  department of gynecology and obstetrics department of gynecology and obstetrics, kon...
 Kwd_count | 51
-RECORD 1-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 53874492
 text      |  characterization of maternal plasma biomarkers associated with delivery of small and large for gestational age infants in the mirec study cohort published: november 1, 2018  premkumari kumarathasan id *premkumari.kumarathasan@hc-sc.gc.ca  environmental health science and research bureau healthy ...
 Kwd_count | 24
-RECORD 2-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 4901995
 text      |  case report in vitro fertilization using luteinizing hormone-releasing hormone injections resulted in healthy triplets without increased attack rates in a hereditary angioedema case published 13 february 2018  ceyda tunakan dalgjç  department of internal medicine division of allergy and clinical...
 Kwd_count | 27
-RECORD 3-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 268424763
 text      |   14 march 2024  mdcindy m martin cmmartin2@houstonmethodist.org  houston methodist debakey heart & vascular center houstontexas, us  houston methodist debakey heart & vascular center houstontexas, us 14 march 202496ee25448631b3b0dec6415cce08145d10.14797/mdcvj.1368submitted: 15 february 2024 acce...
 Kwd_count | 16
-RECORD 4-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 256223001
 text      |  burden and trend of macrosomia and large-for-gestational-age neonates attributable to high pre-pregnancy body mass index in china, 2013-2017: a population-based retrospective cohort study   warren ruktanonchai  shuai zeng  institute of epidemiology and statistics school of public health lanzhou ...
 Kwd_count | 44
-RECORD 5-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 199037976
 text      |  clinical course in a patient with myopathic vlcad deficiency during pregnancy with an affected baby   kenji yamada k-yamada@med.shimane-u.ac.jp  department of pediatrics faculty of medicine shimane university izumo, shimanejapan  keiichi matsubara  department of obstetrics and gynecology ehime u...
 Kwd_count | 20
-RECORD 6-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 42468435
 text      |  detection of anti-cmv igm and anti-toxoplasma gondii igg in pregnant women with history of abortion   saeed kholam  department of medical microbiology college of medicine hawler medical university erbiliraq  zagros kamal al-barzanjy  department of medical microbiology college of medicine hawler ...
 Kwd_count | 16
-RECORD 7-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 248985910
 text      |  evaluating the effect of bolsa familia, brazil's conditional cash transfer programme, on maternal and child health: a study protocol   ila rocha  falcão id  school of nutrition federal university of bahia salvadorbrazil  centre for data and knowledge integration for health (cidacs) oswaldo cruz ...
 Kwd_count | 17
-RECORD 8-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 51698536
 text      |    326 DR J. M. DUNCAN ON THE THEORY OF   Since the time of the Hunters, physiologists have taught that one of the earliest results of successful impregnation, is the formation or deposition of a new membrane in the cavity of the uterus. This membrane, the caduca of Harvey, and to which William H...
 Kwd_count | 12
-RECORD 9-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 4840210
 text      |  social ecological factors and intimate partner violence in pregnancy   bosena tebeje gashaw  college of health sciences jimma university jimmaethiopia  faculty of medicine university of oslo oslo, norway  berit schei  department of public health and nursing faculty of medicine and health science...
 Kwd_count | 59
-RECORD 10----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 80628495
 text      |  review article effect of oxidative stress on the estrogen-nos-no-k ca channel pathway in uteroplacental dysfunction: its implication in pregnancy complications published 10 february 2019  xiang-qun hu  md center for perinatal biology department of basic sciences loma linda university school of m...
 Kwd_count | 98
-RECORD 11----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 229005378
 text      |  assisted reproductive technologies: psychoneurological, moral-ethical, and socio-cultural aspects 2020  r e v i e w s nevrologiya  neurology   i.m. sechenov first moscow state medical university (sechenov university ministry of health of russia moscow   kursk state medical university ministry of...
 Kwd_count | 14
-RECORD 12----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 52944358
 text      |     Art. IV.--A Case of Fibrous Tumour of the Uterus terminating fatally three weeks after Delivery, with observations on diseases of this character. (Accompanied by an Engraving.) By J. T. Ingleby, M. R. C. S., Lecturer on Midwifery, Birmingham.Mrs P. having been previously in perfect health, an...
 Kwd_count | 13
-RECORD 13----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid  | 79513965

In [ ]:
output_parquet_path_1 = dtset_dir_parquet.joinpath("df_pregnancy")
df_papers_pregnancy.write.parquet(output_parquet_path_1.as_posix())
print(f"DataFrame saved as Parquet file at: {output_parquet_path_1}")

DataFrame saved as Parquet file at: /content/drive/MyDrive/Proyecto_RICORS/Parquet/df_pregnancy

Load df_pregnancy

In [ ]:
output_parquet_path_1 = dtset_dir_parquet.joinpath("df_pregnancy")
df_papers_pregnancy = spark.read.parquet(output_parquet_path_1.as_posix())

### **Filtrado por hipertensión**

En esta etapa se refina aún más el conjunto de documentos seleccionando únicamente aquellos que están relacionados con hipertensión.

In [ ]:
## Keyword filter

from pyspark.sql.functions import udf, col, substring, regexp_replace
from pyspark.sql.types import IntegerType

def filter_kwd(dataframe, text_column, keywords_list, end_index, threshold):
    # Define a user-defined function (UDF) to count keyword occurrences
    count_kwds_udf = udf(lambda text: sum(text.lower().count(keyword.lower()) for keyword in keywords_list), IntegerType())

    # Replace punctuation with spaces
    dataframe = dataframe.withColumn("cleaned_text", regexp_replace(substring(col(text_column), 1, end_index), "-", " "))

    #dataframe.show(n=15, truncate=300, vertical=True)

    # Add a column to the DataFrame containing the keyword counts
    dataframe = dataframe.withColumn("Kwd_count", count_kwds_udf(col("cleaned_text")))

    # Filter rows based on the keyword count threshold
    filtered_dataframe = dataframe.filter(col("Kwd_count") >= threshold)

    # Drop the temporary cleaned_text column if not needed
    filtered_dataframe = filtered_dataframe.drop("cleaned_text")

    return filtered_dataframe

In [ ]:
from pyspark.sql.functions import lit

def filter_keywords(dataframe, text_column, keywords_list, end_index, threshold):

    filtered_dataframe = filter_kwd(dataframe, text_column, keywords_list, end_index, threshold)
    updated_rows = []

    #symptom_caused = {}
    symptom_list = []
    counter_list = []
    for row in filtered_dataframe.collect():
      if row[text_column] is not None:
          #print('-------------')
          #print('NEW ROW')
          corpusid = row['corpusid']
          text = row[text_column][:end_index]
          symptom_caused = {}
          max_symptom = 0
          max_counter = 0
          for keyword in keywords_list:
              counter = text.lower().count(keyword.lower())
              if counter >= (threshold):
                  if counter > max_counter:
                      max_counter = counter
                      max_symptom = keyword
          updated_rows.append((corpusid, text, max_symptom, max_counter))
      else:
         continue

    # Definir el esquema del DataFrame
    schema = StructType([
        StructField("corpusid", StringType(), True),
        StructField("text", StringType(), True),
        StructField("Keyword", StringType(), True),
        StructField("counter", IntegerType(), True)
    ])

    # Crear el DataFrame con el esquema definido
    df_updated = spark.createDataFrame(updated_rows, schema)
    df_updated = df_updated.filter(col("counter") > 1)

    return df_updated

In [ ]:
# PRUEBA 3
hypertension_keywords = ["hypertension", "high blood pressure", "pre-eclampsia", "eclampsia", "gestational hypertension"]
df_papers_hypertension = filter_keywords(df_papers_pregnancy, 'text', hypertension_keywords,end_index= 20000, threshold=6)
print('Number of documents in dataset:', df_papers_hypertension.count())
df_papers_hypertension.show(n=15, truncate=300, vertical=True)

Number of documents in dataset: 110
-RECORD 0----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 53874492
 text     |  characterization of maternal plasma biomarkers associated with delivery of small and large for gestational age infants in the mirec study cohort published: november 1, 2018  premkumari kumarathasan id *premkumari.kumarathasan@hc-sc.gc.ca  environmental health science and research bureau healthy ...
 Keyword  | hypertension
 counter  | 8
-RECORD 1----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 246165778
 text     |  long term miscarriage-related hypertension and diabetes mellitus. evidence from a united kingdom population-based cohort study   kelvin okoth id  institute of applied health research university of birmingham birminghamunited kingdom  anuradhaa subramanian  institute of applied health research un...
 Keyword  | hypertension
 counter  | 34
-RECORD 2----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 80628495
 text     |  review article effect of oxidative stress on the estrogen-nos-no-k ca channel pathway in uteroplacental dysfunction: its implication in pregnancy complications published 10 february 2019  xiang-qun hu  md center for perinatal biology department of basic sciences loma linda university school of m...
 Keyword  | eclampsia
 counter  | 14
-RECORD 3----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 9642832
 text     |  effects of anti-lipid peroxidation of punica granatum fruit extract in endothelial cells induced by plasma of severe pre-eclamptic patients-nc-nd license (http://creativecommons.org/ licenses/by-nc-nd/4.0/) available online 15 september 2017  isri nasifah  midwifery programme central of java ngu...
 Keyword  | eclampsia
 counter  | 39
-RECORD 4----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 6914144
 text     |  maternal preeclampsia and neonatal outcomes hindawi publishing corporationcopyright hindawi publishing corporation  carl h backes  department of pediatrics college of medicine the ohio state university and nationwide children's hospital 700 children's drive43205columbusohusa  kara markham  depar...
 Keyword  | eclampsia
 counter  | 65
-RECORD 5----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 15804641
 text     |  Articles Maternal Tobacco Smoke Exposure and Persistent Pulmonary Hypertension of the Newborn   Cynthia Bearer  Renee K Emerson  Mary Ann O&apos;riordan  Esther Roitman  Cedric Shackleton2   1Case Western Reserve University 44106-6010ClevelandOHUSA   2Children's Hospital Oakland Research Institu...
 Keyword  | hypertension
 counter  | 6
-RECORD 6----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 7164064
 text     |  improved pregnancy outcome in type 1 diabetic women with microalbuminuria or diabetic nephropathy effect of intensified antihypertensive therapy?   ringholm lene  mdnielsen  department of endocrinology faculty of health sciences rigshospitalet, copen-hagendenmark  md, dmscpeter damm  department ...
 Keyword  | eclampsia
 counter  | 12
-RECORD 7----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 232059896
 text     |  long-term association of pregnancy and maternal brain structure: the rotterdam study 2022  jurate aleknaviciute  department of psychiatry university medical center rotterdam erasmusmc  · tavia  e evans  department of clinical genetics erasmus mc university medical center rotterdam wytemaweg 9030...
 Keyword  | eclampsia
 counter  | 6
-RECORD 8----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 248521195
 text     |  platelet mitochondrial membrane depolarization reflects disease severity in patients with preeclampsia   bjoern f kraemer  irina hennis  anne karge  anne katrin kraemer  tobias f dreyer  marion kiechle  bettina kuschel  holger bronger  platelet mitochondrial membrane depolarization reflects dise...
 Keyword  | eclampsia
 counter  | 21
-RECORD 9----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 15980393
 text     |      division of neonatology hospital de são joão portoportugal   division of neonatology centro hospitalar do porto portoportugal   division of immunology hospital de são joão portoportugal   department of hygiene and epidemiology faculty of medicine porto university portoportugal   division of ...
 Keyword  | eclampsia
 counter  | 6
-RECORD 10---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 182134952
 text     |  spectrum of foeto-maternal outcome in jaundice with pregnancy: an insight   drritu khatuja  department of obg bsa medical college & hospital rohini, delhidr  department of obg bsa medical college & hospital rohini, delhidr  drn sarda  postgraduate department of obg bsa medical college & hospital...
 Keyword  | eclampsia
 counter  | 7
-RECORD 11---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 55477912
 text     |  serum magnesium levels in mild and severe preeclampsia and normal pregnant women mar 12. 2015. 2015. march 12  r sujatha  c h madhuri  k v sudhamadhuri  t radha  serum magnesium levels in mild and severe preeclampsia and normal pregnant women  journal of evolution of medical and dental sciences ...
 Keyword  | eclampsia
 counter  | 71
-RECORD 12---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 219683936
 text     |  neuro-imaging in severe hypertensive disorders of pregnancy: a study from north indian tertiary health care institution june 2020. 2346. 2020 jun  gynecology dogra  r  neuro-imaging in severe hypertensive disorders of pregnancy: a study from north indian tertiary health care institution  int j r...
 Keyword  | eclampsia
 counter  | 25
-RECORD 13---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 203465462
 text     |  the effects of phaleria macrocarpa (scheff.) boerl extract on malondialdehyde (mda) level in preeclampsia-induced human umbilical vein endothelial cell (huvec) culture   l simanjuntak :leosimanjuntak66@gmail.com  doctoral program faculty of medicine universitas sumatera utara medanindonesia  dep...
 Keyword  | eclampsia
 counter  | 77
-RECORD 14---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 250953586
 text     |  medicine ® identification of underlying mechanisms and hub gene-mirna networks of the genomic subgroups in preeclampsia development   md a ,min zhang  mdxiaheng deng  md a ,ziyan jiang  mdzhiping ge  medicine ® identification of underlying mechanisms and hub gene-mirna networks of the genomic su...
 Keyword  | eclampsia
 counter  | 15
only showing top 15 rows

In [ ]:
output_parquet_path_2 = dtset_dir_parquet.joinpath("df_pregnancy_hypertension")
df_papers_hypertension.write.parquet(output_parquet_path_2.as_posix())
print(f"DataFrame saved as Parquet file at: {output_parquet_path_2}")

DataFrame saved as Parquet file at: /content/drive/MyDrive/Proyecto_RICORS/Parquet/df_pregnancy_hypertension

Load df_pregnancy_hypertension

In [ ]:
output_parquet_path_2 = dtset_dir_parquet.joinpath("df_pregnancy_hypertension")
df_papers_hypertension = spark.read.parquet(output_parquet_path_2.as_posix())

### **Filtrado por fármacos**

En esta etapa se refina aún más el conjunto de documentos seleccionando únicamente aquellos que están relacionados con fármarcos de interés. El proceso consiste en:

Filtrar los textos mediante palabras clave asociadas a síntomas específicos, tales como:

* **Labetalol**
* **Nifedipine**
* **Methyldopa**
* **Hydralazine**

Este filtrado permite enfocar el análisis en publicaciones científicas relevantes para los fármacos  más comunes para tratar la hipertensión en el embarazo.

In [ ]:
keyword_list_symptoms = [ "labetalol", "nifedipine", "methyldopa", "hydralazine",
    "beta blocker", "calcium channel blocker", "vasodilator"]
df_papers_hypertensive_drugs = filter_keywords(df_papers_hypertension, 'text', keyword_list_symptoms,end_index= 20000, threshold=1)
print('Number of documents in dataset:', df_papers_hypertensive_drugs.count())
df_papers_hypertensive_drugs.show(n=15, truncate=300, vertical=True)

Number of documents in dataset: 5
-RECORD 0----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 7164064
 text     |  improved pregnancy outcome in type 1 diabetic women with microalbuminuria or diabetic nephropathy effect of intensified antihypertensive therapy?   ringholm lene  mdnielsen  department of endocrinology faculty of health sciences rigshospitalet, copen-hagendenmark  md, dmscpeter damm  department ...
 Keyword  | methyldopa
 counter  | 3
-RECORD 1----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 33087877
 text     |  nitric oxide and reactive oxygen species in the pathogenesis of preeclampsia 2015  keiichi matsubara keiichi@m.ehime-u.ac.jp  department of obstetrics and gynecology ehime university school of medicine 791-0295ehimejapan  takashi higaki higaki@m.ehime-u.ac.jp  department of pediatrics ehime univ...
 Keyword  | vasodilator
 counter  | 2
-RECORD 2----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 264358040
 text     |  obesity, thrombosis, venous disease, lymphatic disease, and lipedema: an obesity medicine association (oma) clinical practice statement (cps) 2023 19 october 2023  a r t i c l e i n f o  shagun bindlish  jennifer ng  wissam ghusn wissamghusn7@gmail.com  angela fitch drfitch@knownwell.health.  ha...
 Keyword  | vasodilator
 counter  | 2
-RECORD 3----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 13500056
 text     |  role of lectin-like oxidized low density lipoprotein-1 in fetoplacental vascular dysfunction in preeclampsia published 6 july 2014  felipe a zuniga  department of clinical biochemistry and immunology faculty of pharmacy university of concepción 4070386concepcionchile  valeska ormazabal  departme...
 Keyword  | vasodilator
 counter  | 3
-RECORD 4----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 237338236
 text     |  hydatidiform mole with coexisting fetus and syndrome of inappropriate antidiuretic hormone secretion: a case report 2021  riley mickelsen  school of medicine university of kansas 66160kansas cityksusa;  valerie french  department of obstetrics and gynecology university of kansas 66160kansas city...
 Keyword  | nifedipine
 counter  | 2

In [ ]:
#keyword_list_symptoms = ["labetalol", "nifedipine", "methyldopa", "hydralazine"]
keyword_list_symptoms = ["antihypertensive", "labetalol", "nifedipine", "methyldopa", "hydralazine",
    "beta blocker", "calcium channel blocker", "vasodilator"]
df_papers_hypertensive_drugs = filter_keywords(df_papers_hypertension, 'text', keyword_list_symptoms,end_index= 20000, threshold=1)
print('Number of documents in dataset:', df_papers_hypertensive_drugs.count())
df_papers_hypertensive_drugs.show(n=15, truncate=300, vertical=True)

Number of documents in dataset: 14
-RECORD 0----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 7164064
 text     |  improved pregnancy outcome in type 1 diabetic women with microalbuminuria or diabetic nephropathy effect of intensified antihypertensive therapy?   ringholm lene  mdnielsen  department of endocrinology faculty of health sciences rigshospitalet, copen-hagendenmark  md, dmscpeter damm  department ...
 Keyword  | antihypertensive
 counter  | 35
-RECORD 1----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 219683936
 text     |  neuro-imaging in severe hypertensive disorders of pregnancy: a study from north indian tertiary health care institution june 2020. 2346. 2020 jun  gynecology dogra  r  neuro-imaging in severe hypertensive disorders of pregnancy: a study from north indian tertiary health care institution  int j r...
 Keyword  | antihypertensive
 counter  | 2
-RECORD 2----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 701611
 text     |  associations between body mass index and development of metabolic disorders in fertile women-a nationwide cohort study   md;michelle dalgas schmiegelow  mdcharlotte andersson  phd;lars køber  mddmsci ; søren  mdskøtt andersen  phd; mette  mdlykke norgaard  phd; thomas  md;bo jensen  mdgunnar gis...
 Keyword  | antihypertensive
 counter  | 4
-RECORD 3----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 59259444
 text     |  renalase as a biomarker in gestations with preeclampsia september 2018. 2018  heba abdelbasset allam  obstetrics and gynecology department ain shams university egypt  dalal elsayed abdelaal  clinical pathology department ain shams university egypt  renalase as a biomarker in gestations with pree...
 Keyword  | antihypertensive
 counter  | 2
-RECORD 4----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 33087877
 text     |  nitric oxide and reactive oxygen species in the pathogenesis of preeclampsia 2015  keiichi matsubara keiichi@m.ehime-u.ac.jp  department of obstetrics and gynecology ehime university school of medicine 791-0295ehimejapan  takashi higaki higaki@m.ehime-u.ac.jp  department of pediatrics ehime univ...
 Keyword  | vasodilator
 counter  | 2
-RECORD 5----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 16063697
 text     |  case report gestational weight gain and peripartum cardiomyopathy in a twin pregnancy   hiroko matsumiya  department of obstetrics and gynecology hakodate central general hospital 040-8585hakodatejapan  naotaka saito  department of cardiovascular medicine hakodate central general hospital 040-85...
 Keyword  | antihypertensive
 counter  | 2
-RECORD 6----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 264358040
 text     |  obesity, thrombosis, venous disease, lymphatic disease, and lipedema: an obesity medicine association (oma) clinical practice statement (cps) 2023 19 october 2023  a r t i c l e i n f o  shagun bindlish  jennifer ng  wissam ghusn wissamghusn7@gmail.com  angela fitch drfitch@knownwell.health.  ha...
 Keyword  | vasodilator
 counter  | 2
-RECORD 7----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 225639574
 text     |  black cumin (nigella sativa) effect on blood pressure, mean arterial pressure, proteinuria in preeclamptic model rats   johny marpaung drjohnymarpaung@gmail.com  department of obstetric and gynaecology medical faculty universitas sumatera utara general hospital h. adam malik medan   m f g sirega...
 Keyword  | antihypertensive
 counter  | 4
-RECORD 8----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 252113829
 text     |  a personal history of research on hypertension from an encounter with hypertension to the development of hypertension practice based on out-of-clinic blood pressure measurements 2022  yutaka imai  a personal history of research on hypertension from an encounter with hypertension to the developme...
 Keyword  | antihypertensive
 counter  | 3
-RECORD 9----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 220500483
 text     |  maternal hypertensive disorders and subtypes of hypospadias: a dutch case-control study 2020  hussein jamaladin  department for health evidence radboud institute for health sciences radboud university medical center nijmegenthe netherlands  iris a l m van rooij  department for health evidence ra...
 Keyword  | antihypertensive
 counter  | 13
-RECORD 10---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 240076751
 text     |  incidence and determinants of adverse outcomes among women who were managed for eclampsia in the university of gondar comprehensive specialized hospital, northwest ethiopia open access   yisfa getaneh  department of human anatomy school of medicine college of medicine and health sciences univers...
 Keyword  | antihypertensive
 counter  | 2
-RECORD 11---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 55284717
 text     |  maternal outcome of pregnant mothers with hypertensive disorder of pregnancy at hospitals in wolaita zone, southern ethiopia. j preg child health 5: 375. j preg child health, an open access journal issn: 2376-127x citation: obsa ms 2018. 2018. 2018. 2018. 2018  wolka suleiman obsa  m s obsa  e w...
 Keyword  | antihypertensive
 counter  | 2
-RECORD 12---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 13500056
 text     |  role of lectin-like oxidized low density lipoprotein-1 in fetoplacental vascular dysfunction in preeclampsia published 6 july 2014  felipe a zuniga  department of clinical biochemistry and immunology faculty of pharmacy university of concepción 4070386concepcionchile  valeska ormazabal  departme...
 Keyword  | vasodilator
 counter  | 3
-RECORD 13---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 corpusid | 237338236
 text     |  hydatidiform mole with coexisting fetus and syndrome of inappropriate antidiuretic hormone secretion: a case report 2021  riley mickelsen  school of medicine university of kansas 66160kansas cityksusa;  valerie french  department of obstetrics and gynecology university of kansas 66160kansas city...
 Keyword  | nifedipine
 counter  | 2

In [ ]:
# Saving in the Data Lake
output_parquet_path_3 = dtset_dir_parquet.joinpath("df_hypertensive_drugs_2")
df_papers_hypertensive_drugs.write.parquet(output_parquet_path_3.as_posix())
print(f"DataFrame saved as Parquet file at: {output_parquet_path_3}")

DataFrame saved as Parquet file at: /content/drive/MyDrive/Proyecto_RICORS/Parquet/df_hypertensive_drugs_2

### **Función de reconocimiento de entidades con GPT**

Este proceso utiliza modelos de lenguaje (GPT) para identificar y extraer automáticamente entidades relevantes dentro de los textos científicos. Las etapas que lo componen son:

1. **Diseño del prompt:** se formula cuidadosamente una instrucción que guía al modelo para extraer información específica sobre protocolos de tDCS.

2. **Extracción en formato JSON:** el modelo responde estructurando los datos en formato JSON, lo cual facilita su interpretación y procesamiento automatizado.

3. **Generación de DataFrame:** los datos extraídos se organizan en un DataFrame para su análisis posterior e integración en el sistema de recomendación.

In [ ]:
GPT_api_key = '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'

In [ ]:
## EJEMPLO HYPERTENSION
def NER(text):
    client = OpenAI(api_key=GPT_api_key)
    response = client.chat.completions.create(
        model="gpt-4-turbo",
        response_format={"type": "json_object"},
        messages=[
            {
                "role": "system",
                "content": (
                    "You are an expert in natural language processing for biomedical literature. "
                    "Your task is to extract named entities from scientific articles related to **antihypertensive treatments during pregnancy**, "
                    "specifically from clinical trials. You must respond strictly in JSON format. "
                    "Extract the following information:\n\n"
                    "1. **Antihypertensive drug(s)** used (e.g., labetalol, nifedipine, methyldopa).\n"
                    "2. **Drug dosage and route of administration** (e.g., 100 mg orally, IV hydralazine 5 mg).\n"
                    "3. **Therapy schedule**: number of doses per day, duration in days/weeks, total duration of treatment.\n"
                    "4. **Type of hypertension** treated (e.g., gestational hypertension, preeclampsia, chronic hypertension).\n"
                    "5. **Gestational age at treatment start** (e.g., 28 weeks, third trimester).\n"
                    "6. **Study design/methodology** (e.g., randomized controlled trial, double-blind, open-label).\n"
                    "7. **Primary outcomes evaluated** (e.g., blood pressure control, maternal adverse events, fetal outcomes).\n"
                    "8. **Effectiveness**: Did the drug show a positive effect on primary outcomes? (YES/NO).\n"
                    "9. **Sample size** (number of pregnant participants).\n"
                    "10. **Any maternal or fetal side effects** mentioned (e.g., hypotension, fetal bradycardia).\n"
                    "11. **Paper title**\n"
                    "12. **DOI**\n"
                    "13. **Year of publication**\n\n"
                    "If any item is not found in the text, use 'Not specified' or an empty list."
                )
            },
            {
                "role": "user",
                "content": (
                    "Your extracted entities must follow this JSON structure:\n\n"
                    "{\n"
                    "  'Year': ['year'],\n"
                    "  'Title': ['title'],\n"
                    "  'DOI': ['doi'],\n"
                    "  'Drug': ['drug_name'],\n"
                    "  'Dosage': ['dosage_and_route'],\n"
                    "  'Therapy_schedule': ['doses_per_day'],\n"
                    "  'Treatment_duration': ['duration_days_weeks'],\n"
                    "  'Hypertension_type': ['hypertension_type'],\n"
                    "  'Gestational_age_start': ['gestational_age'],\n"
                    "  'Study_design': ['study_design'],\n"
                    "  'Primary_outcomes': ['outcomes'],\n"
                    "  'Effectiveness': ['effectiveness_yes_no'],\n"
                    "  'N_sample': ['n_participants'],\n"
                    "  'Side_effects': ['side_effects']\n"
                    "}\n\n"
                    "Please return only the structured JSON object with no additional explanation or formatting."
                )
            },
            {
                "role": "user",
                "content": text
            }
        ],
        temperature=0,
        top_p=1,
        frequency_penalty=0,
        presence_penalty=0
    )
    result = response.choices[0].message.content.strip(" \n")
    return result

In [ ]:
def parameter_extraction(df):

    df_protocolo_parameters = []
    references_keyword = "Acknowledgments"

    # Adjust the batch size as needed for testing or production
    df_selected = df.head(10)  # Use df.head(df.count()) for full dataset
    # df_selected = df.head(df.count())
    for record in df_selected:
        try:
            text = str(record.text.replace('\n', ' '))
            corpusid = record.corpusid
            Keyword = getattr(record, "Keyword", None)

            # Truncate text before references
            references_index = text.find(references_keyword)
            if references_index != -1:
                text = text[:references_index]

            # Call GPT NER function
            result = NER(text)

            # Extract structured information
            extracted_info = extract_info_from_json(result)

            if extracted_info is None:
                print(f"[SKIP] Could not extract info for corpusid {corpusid}")
                print(f"Raw GPT output: {result}")
                continue

            extracted_info["corpusid"] = corpusid
            if Keyword:
                extracted_info["Keyword"] = Keyword  # Only add if present

            df_protocolo_parameters.append(extracted_info)

        except Exception as e:
            print(f"[ERROR] Processing corpusid {record.corpusid}: {e}")
            continue

    # Convert list of dictionaries to DataFrame
    df_protocolo_parameters = pd.DataFrame(df_protocolo_parameters)

    return df_protocolo_parameters

In [ ]:
# "antihypertensive", "labetalol", "nifedipine", "methyldopa", "hydralazine", "beta blocker", "calcium channel blocker", "vasodilator"
df_protocolo_parameters = parameter_extraction(df_papers_hypertensive_drugs)
df_protocolo_parameters.head(14)

,Year,Title,DOI,Drug,Dosage,Therapy_schedule,Treatment_duration,Hypertension_type,Gestational_age_start,Study_design,Primary_outcomes,Effectiveness,N_sample,Side_effects,corpusid
0,2006,Improved pregnancy outcome in type 1 diabetic ...,Not specified,Methyldopa,Not specified,Not specified,Not specified,Diabetic nephropathy,First trimester,Prospective study,Blood pressure control,YES,117,Not specified,7164064
1,2020,Neuro-imaging in severe hypertensive disorders...,10.18203/2320-1770.ijrcog20202310,Magnesium sulphate,Pritchard's regimen,Not specified,1 year,Severe preeclampsia,20 weeks or beyond,Descriptive observational study,Neurological involvement detected on MRI,YES,65,Not specified,219683936
2,Not specified,Not specified,Not specified,None,None,None,None,None,None,None,None,None,None,None,701611
3,2018,Renalase as a Biomarker in Gestations with Pre...,10.19080/JGWH.2018.11.555816,None,None,None,None,Preeclampsia,Third trimester,Observational study,Serum renalase levels,YES,150,None,59259444
4,2015,Nitric oxide and reactive oxygen species in th...,10.3390/ijms16034600,None,None,None,None,preeclampsia,None,None,None,None,None,None,33087877
5,2015,Case Report: Gestational Weight Gain and Perip...,10.1155/2015/317146,None,None,None,None,Preeclampsia,32 weeks,Case report,Diagnosis of preeclampsia and peripartum cardi...,Not specified,1,"Proteinuria, orthopnea, cough, dyspnea",16063697
6,2023,"Obesity, Thrombosis, Venous Disease, Lymphatic...",10.1016/j.obpill.2023.100092,None,None,None,None,None,None,None,None,None,None,None,264358040
7,2020,Black Cumin (Nigella Sativa) Effect on Blood P...,10.22159/ijcpr.2020v12i4.39099,Black Cumin seed extract (Nigella Sativa),500 mg/kg/day orally,1 dose per day,15 days,Preeclampsia,Not specified,True experimental design,Systolic and diastolic blood pressure,YES,24,No side effects reported,225639574
8,2022,A personal history of research on hypertension...,Not specified,None,None,None,None,None,None,None,None,None,None,None,252113829
9,2020,Maternal Hypertensive Disorders and Subtypes o...,10.1111/ppe.12683,None,None,None,None,Preeclampsia,None,Case-control study,Association between maternal hypertensive diso...,NO,887 cases and 1005 controls,None,220500483
10,2021,Incidence and determinants of adverse outcomes...,10.1186/s12884-021-04199-1,None,None,None,None,Eclampsia,None,Retrospective follow-up study,Adverse maternal outcomes of eclampsia,Not specified,231,Abruption placentae,240076751
11,2018,Maternal outcome of pregnant mothers with hype...,10.4172/2376-127X.1000375,Not specified,Not specified,Not specified,Not specified,preeclampsia,Not specified,cross-sectional study,maternal outcome,Not specified,225,renal failure,55284717
12,2014,Role of Lectin-like Oxidized Low Density Lipop...,10.1155/2014/353616,None,None,None,None,Preeclampsia,None,Review article,None,None,None,None,13500056
13,None,None,None,Hydralazine,Hydralazine 10 mg intravenously,1 dose,Not specified,Severe range hypertension,13 weeks,Case report,Management of hypertension and hyperthyroidism,None,None,Hyponatremia,237338236

In [ ]:
# "labetalol", "nifedipine", "methyldopa", "hydralazine", "beta blocker", "calcium channel blocker", "vasodilator"
df_protocolo_parameters = parameter_extraction(df_papers_hypertensive_drugs)
df_protocolo_parameters.head(10)

,Year,Title,DOI,Drug,Dosage,Therapy_schedule,Treatment_duration,Hypertension_type,Gestational_age_start,Study_design,Primary_outcomes,Effectiveness,N_sample,Side_effects,corpusid
0,2006,Improved pregnancy outcome in type 1 diabetic ...,Not specified,Methyldopa,Not specified,Not specified,Not specified,Diabetic nephropathy,First or second visit,Prospective study,Blood pressure control,YES,117,Not specified,7164064
1,2015,Nitric oxide and reactive oxygen species in th...,10.3390/ijms16034600,None,None,None,None,preeclampsia,None,None,None,None,None,None,33087877
2,2023,"Obesity, Thrombosis, Venous Disease, Lymphatic...",10.1016/j.obpill.2023.100092,None,None,None,None,None,None,None,None,None,None,None,264358040
3,2014,Role of Lectin-like Oxidized Low Density Lipop...,10.1155/2014/353616,None,None,None,None,Preeclampsia,None,Review article,None,None,None,None,13500056
4,2021,Hydatidiform mole with coexisting fetus and sy...,10.1210/jendso/bvab129,Hydralazine,Hydralazine 10 mg intravenously,1 dose,Not specified,Severe range hypertension,13 weeks,Case report,Management of hypertension,YES,1,Hyponatremia,237338236

In [ ]:
## Saving in the Data Lake as df_BBDD_original (as csv and Excel)
output_parquet_path_3 = dtset_dir_parquet.joinpath("df_gpt_parameters")
df_protocolo_parameters.to_csv(output_parquet_path_3, index=False)
print(f"DataFrame saved as Parquet file at: {output_parquet_path_3}")

DataFrame saved as Parquet file at: /content/drive/MyDrive/Proyecto_RICORS/Parquet/df_gpt_parameters